In [8]:
import pandas as pd

In [9]:
import re

#NORMALIZE_NAME: the function takes the subject path basename and splits it according to the underscore
#in order to take the first string and use it as index in dataframe.
#If a string is repeated, the function adds the first letter of the second string after the underscore

def normalize_name(subject_path, add_name):
    #Components= []
    subject = os.path.basename(subject_path)
    subject = re.sub(r'^(DE|D|DI|LO|DEL)_', '', subject)
    components =  subject.split("_")
    if add_name[0]==components[0] or add_name[1]==components[0] or add_name[2]==components[0] :
            return components[0].title() + components[1][0].capitalize()
    else:
            return components[0].title()

In [28]:
import os

#GET_SUBJECT_METADATA:the function recives, as input, the subject path and the list of name repeated already known
#the output are the path base name (SURNAME_NAME) and the normalized name
#add_name needs to contain the list of name repeated

def get_subject_metadata(subject_path, subjects_with_name=[]):
    dirname = os.path.basename(subject_path)
    return [dirname, normalize_name(subject_path, add_name=[name for name in subjects_with_name])]

In [33]:
import pandas as pd
import glob

datasetDir = "/data/RMN/dataset-gliomi/scaled"

SUBJECT_NAME_REPEATED=["BIANCHI","BOVE","PROIETTI"]

# PATIENT_REMOVED=['Mitchell','Pascal','Mgmt','Barontini','Bergnach','Bernola',
#                 'Catalani','Colafrancesco','Colamartini','Coletta','Angeli',
#                 'Darida','Maso','Federico','Fiucci','Ionta','Lupo','Martella',
#                 'Masci','Medici','Monacelli','Musat','Palmieri','Pierini',
#                 'Podagrosi','ProiettiM','Testa','Tiberi','Tomao','Veronesi',
#                 'Zangari','Rufini','Farella']

subjects_paths = []

#Path and Subject columns
# subjects_path = pd.DataFrame()

for subject_path in glob.glob(f"{datasetDir}/*"):
    
    if subject_path.endswith(".csv"):
        continue

    if subject_path.endswith(".xlsx"):
        continue
        
    if subject_path.endswith("CSV_DATA"):
        continue
        
    subjects_path = get_subject_metadata(subject_path , subjects_with_name=[SUBJECT_NAME for SUBJECT_NAME in SUBJECT_NAME_REPEATED])
    
    print(subjects_path)
    
    subjects_paths.append(subjects_path)

df_subject_dirs = pd.DataFrame(subjects_paths, columns=["Path", "Subject"], ignore_index=True)
    
# subjects_path = pd.concat([subjects_path, df_subject_dirs], ignore_index=True)

['ALESSANDRINI_GLAUCO', 'Alessandrini']
['ANGELONI_GIUSEPPINA', 'Angeloni']
['ASSANTO_MARIA', 'Assanto']
['ASTA_G', 'Asta']
['BAGNOLI_VINCENZO', 'Bagnoli']
['BALZAMO_A', 'Balzamo']
['BARONTINI_MARIA_GIOVANNA', 'Barontini']
['BATTISTA_DOMENICA', 'Battista']
['BERGNACH_SILVANO', 'Bergnach']
['BERNOLA_TERESA', 'Bernola']
['BERTUZZI_LUISA', 'Bertuzzi']
['BEVILACQUA_RITA', 'Bevilacqua']
['BIANCHI_GIOVANNI', 'BianchiG']
['BIANCHI_ORAZIO', 'BianchiO']
['BIANCHI_S', 'BianchiS']
['BIAVATI_S', 'Biavati']
['BOEZI_MARIO', 'Boezi']
['BOVE_A', 'BoveA']
['CACACE_PAOLO', 'Cacace']
['CALDARONI_ANNA', 'Caldaroni']
['CAMACCI_FILIBERTO', 'Camacci']
['CAMPLESE_CANDEROLA', 'Camplese']
['CAPEZZONE', 'Capezzone']
['CARULLI_L', 'Carulli']
['CARZEDDA_PAOLO', 'Carzedda']
['CATALANI_F', 'Catalani']
['CELLINI_T', 'Cellini']
['CHERRI_M', 'Cherri']
['CIMPUREANU_N', 'Cimpureanu']
['COLAFRANCESCO_ROCCO', 'Colafrancesco']
['COLAMARTINI_GIUSEPPINA', 'Colamartini']
['COLAZZO_LUIGI_GIUSEPPE', 'Colazzo']
['COLETTA_MARIA', 'Coletta']
['COSIMI_MASSIMO', 'Cosimi']
['COSTANZI_P', 'Costanzi']
['CRESCENZI_ARMANDO', 'Crescenzi']
['DARIDA', 'Darida']
['DEL_BOVE_PIERINA', 'BoveP']
['DE_PAOLI_R', 'Paoli']
['DE_SANTIS_GIORGO', 'Santis']
['DIASPRO_G', 'Diaspro']
['DI_CARLATONIO_MAURIZIO', 'Carlatonio']
['DI_LORENZO_TOMMASO', 'Lorenzo']
['DI_MARCO_L', 'Marco']
['DI_MASO_SIMONE', 'Maso']
['DI_MASSA_SERGIO', 'Massa']
['DOBRISAN_DORINA', 'Dobrisan']
['DROGHEI_SANDRO', 'Droghei']
['D_ANGELI_ANNUNZIATA', 'Angeli']
['D_ANGELO_RENATO', 'Angelo']
['EMERY_R_C', 'Emery']
['FABIANI_ANNA', 'Fabiani']
['FARELLA_PAOLO', 'Farella']
['FEDERICO_FRANCESCO', 'Federico']
['FERRAZZA_RITA', 'Ferrazza']
['FERRI_M_B', 'Ferri']
['FILIPPONI_QUINTINO', 'Filipponi']
['FIUCCI_A', 'Fiucci']
['FLORIO_FRANCESCO_PAOLO', 'Florio']
['FRATINI_RITA', 'Fratini']
['GATTAMORTA_NATALINA', 'Gattamorta']
['GEGGI_GIULIO', 'Geggi']
['GENNARI_CRISTIANO', 'Gennari']
['GIACCHERINI_M', 'Giaccherini']
['GIANFELICI_LUISA', 'Gianfelici']
['GIOIA_COSMO_DAMIANO', 'Gioia']
['GIORDANO_STEFANIA', 'Giordano']
['INCITI_DONATA', 'Inciti']
['IONTA_LUCIANA', 'Ionta']
['ISMAIL_A', 'Ismail']
['ISONI_FRANCESCO', 'Isoni']
['LABELLA_ADRIANA', 'Labella']
['LANDONE_ANNUNZIATA', 'Landone']
['LIBERATI_G_L', 'Liberati']
['LIOCE_CARMELA', 'Lioce']
['LONGO_ROSALIA', 'Longo']
['LO_BELLO_MARIO', 'Bello']
['LUPI_GIANCARLO', 'Lupi']
['LUPO_ASSUNTA', 'Lupo']
['MAIOLINI_SANTA', 'Maiolini']
['MARAGNO_CLARA', 'Maragno']
['MARCOLINI', 'Marcolini']
['MARCONI_E', 'Marconi']
['MARIANI_BERNARDO', 'Mariani']
['MAROCCHI_CORRADO', 'Marocchi']
['MARTELLA_COSIMO', 'Martella']
['MARTINEZ', 'Martinez']
['MASCI_ADA', 'Masci']
['MEDICI_GIOVANNA', 'Medici']
['MICHELI_MICHELE', 'Micheli']
['MITCHELL_CHARLENE_ANN', 'Mitchell']
['MONACELLI_LAURA', 'Monacelli']
['MONTI_E', 'Monti']
['MOSCARDINI_GIACINTO', 'Moscardini']
['MOVIA_A', 'Movia']
['MUSAT_DORINA', 'Musat']
['NERONE_GIANLUCA', 'Nerone']
['NERVEGNA_G', 'Nervegna']
['ORLANDI_PAOLO', 'Orlandi']
['PAGANNONE_GIANNI', 'Pagannone']
['PAGLIAROLI_LUCIA', 'Pagliaroli']
['PAGNOTTA', 'Pagnotta']
['PALMA', 'Palma']
['PALMIERI', 'Palmieri']
['PANETTI', 'Panetti']
['PASCAL', 'Pascal']
['PASCARELLA_P', 'Pascarella']
['PASSARI', 'Passari']
['PELUSO_A', 'Peluso']
['PENNICCHI_R', 'Pennicchi']
['PIERI', 'Pieri']
['PIERINI_CATERINA', 'Pierini']
['PINEDA_MARIA_ASSUNTA', 'Pineda']
['PISTOIA_CARLO', 'Pistoia']
['PODAGROSI_TERESA', 'Podagrosi']
['PODDA_ANTONINO', 'Podda']
['POMPEI_F', 'Pompei']
['PRINCIPI_ANNA_MARIA', 'Principi']
['PROIETTI_GIOVANNI', 'ProiettiG']
['PROIETTI_MARIA', 'ProiettiM']
['QUACQUARELLI_A', 'Quacquarelli']
['QUATTROCIOCCHI_EVELINA', 'Quattrociocchi']
['RE_ATTILIO', 'Re']
['RICCI_ALESSANDRO', 'Ricci']
['ROMITO_ORAZIO', 'Romito']
['RONZO_F', 'Ronzo']
['ROSARI_NANDO', 'Rosari']
['RUFINI_A', 'Rufini']
['RUSCITO_ELISABETTA', 'Ruscito']
['RUSNAC_NINA', 'Rusnac']
['RUSSO_IDA', 'Russo']
['SALA_CLARA', 'Sala']
['SALTARELLI_DOMENICO', 'Saltarelli']
['SANTINI_ERMANNO', 'Santini']
['SCARAMUZZA_F', 'Scaramuzza']
['SOLOVIY_VOLODYMYR', 'Soloviy']
['STAN_FLORENTINA', 'Stan']
['STEFANINI_CLORINDA', 'Stefanini']
['STERPA_GIUSEPPE', 'Sterpa']
['SYKULA_GRAZYNA_BARBARA', 'Sykula']
['TAVERNESE_G', 'Tavernese']
['TAVOLUCCI_MARIA_RITA', 'Tavolucci']
['TEMPESTINI_MARISA', 'Tempestini']
['TEMPORIN_PATRIZIA', 'Temporin']
['TEOFILI_STEFANO', 'Teofili']
['TESTA_SERGIO', 'Testa']
['TIBERI_GIUSEPPE', 'Tiberi']
['TOMAO_ANGELO', 'Tomao']
['TOMEO_VINCENZO', 'Tomeo']
['TROSCIA_M', 'Troscia']
['VERONESI_ROCCO', 'Veronesi']
['VESCIA_M_T', 'Vescia']
['VITULANO_RITA', 'Vitulano']
['ZAMPELLA_A', 'Zampella']
['ZANATTA_CARLO', 'Zanatta']
['ZANGARI_ALDO', 'Zangari']
['ZEPPA_ONORIO', 'Zeppa']

TypeError: __init__() got an unexpected keyword argument 'ignore_index'

In [34]:
df_subject_dirs

                    Path       Subject
0    ALESSANDRINI_GLAUCO  Alessandrini
1    ANGELONI_GIUSEPPINA      Angeloni
2          ASSANTO_MARIA       Assanto
3                 ASTA_G          Asta
4       BAGNOLI_VINCENZO       Bagnoli
..                   ...           ...
152        VITULANO_RITA      Vitulano
153           ZAMPELLA_A      Zampella
154        ZANATTA_CARLO       Zanatta
155         ZANGARI_ALDO       Zangari
156         ZEPPA_ONORIO         Zeppa

[157 rows x 2 columns]

In [35]:
anagraph_dataset = pd.read_excel("/data/RMN/dataset-gliomi-cnn/GLIOMI_GRUPPI_DEF.xlsx", decimal=',')

In [36]:
anagraph_dataset = anagraph_dataset.loc[:, ['COGNOME', 'ETA', 'SOPR (gg)']].dropna()

In [37]:
anagraph_dataset.columns = ['Subject', 'Eta', 'Sopr']

In [38]:
result = pd.merge(df_subject_dirs, anagraph_dataset, how='inner', on='Subject', sort=True)

In [92]:
survivor = pd.read_csv('datasets/dataset-survivor.csv')

In [93]:
result1 = pd.merge(result, survivor.loc[:,['Subject','Survival']], how='inner', on='Subject', sort=True)

In [94]:
result1.to_csv('datasets/complete-survivor.csv')

In [95]:
result1

                    Path       Subject   Eta  Sopr  Survival
0    ALESSANDRINI_GLAUCO  Alessandrini  75.0   0.0       0.0
1    ANGELONI_GIUSEPPINA      Angeloni  67.0   1.0       1.0
2          ASSANTO_MARIA       Assanto  62.0   0.0       0.0
3                 ASTA_G          Asta  48.0   1.0       1.0
4       BAGNOLI_VINCENZO       Bagnoli  73.0   1.0       1.0
..                   ...           ...   ...   ...       ...
122           ZAMPELLA_A      Zampella  49.0   1.0       1.0
123        ZANATTA_CARLO       Zanatta  66.0   1.0       1.0
124         ZANGARI_ALDO       Zangari  62.0   0.0       0.0
125         ZEPPA_ONORIO         Zeppa  61.0   0.0       0.0
126         ZEPPA_ONORIO         Zeppa  61.0   0.0       0.0

[127 rows x 5 columns]